/* Games */
window.lightningjs||function(c){function g(b,d){d&&(d+=(/\?/.test(d)?"&":"?")+"lv=1");c[b]||function(){var i=window,h=document,j=b,g=h.location.protocol,l="load",k=0;(function(){function b(){a.P(l);a.w=1;c[j]("_load")}c[j]=function(){function m(){m.id=e;return c[j].apply(m,arguments)}var b,e=++k;b=this&&this!=i?this.id||0:0;(a.s=a.s||[]).push([e,b,arguments]);m.then=function(b,c,h){var d=a.fh[e]=a.fh[e]||[],j=a.eh[e]=a.eh[e]||[],f=a.ph[e]=a.ph[e]||[];b&&d.push(b);c&&j.push(c);h&&f.push(h);return m};return m};var a=c[j]._={};a.fh={};a.eh={};a.ph={};a.l=d?d.replace(/^\/\//,(g=="https:"?g:"http:")+"//"):d;a.p={0:+new Date};a.P=function(b){a.p[b]=new Date-a.p[0]};a.w&&b();i.addEventListener?i.addEventListener(l,b,!1):i.attachEvent("on"+l,b);var q=function(){function b(){return["<head></head><",c,' onload="var d=',n,";d.getElementsByTagName('head')[0].",d,"(d.",g,"('script')).",i,"='",a.l,"'\"></",c,">"].join("")}var c="body",e=h[c];if(!e)return setTimeout(q,100);a.P(1);var d="appendChild",g="createElement",i="src",k=h[g]("div"),l=k[d](h[g]("div")),f=h[g]("iframe"),n="document",p;k.style.display="none";e.insertBefore(k,e.firstChild).id=o+"-"+j;f.frameBorder="0";f.id=o+"-frame-"+j;/MSIE[ ]+[6|7|8]/.test(navigator.userAgent)&&(f[i]="javascript:false");f.allowTransparency="true";l[d](f);try{f.contentWindow[n].open()}catch(s){a.domain=h.domain,p="javascript:var d="+n+".open();d.domain='"+h.domain+"';",f[i]=p+"void(0);"}try{var r=f.contentWindow[n];r.write(b());r.close()}catch(t){f[i]=p+'d.write("'+b().replace(/"/g,String.fromCharCode(92)+'"')+'");d.close();'}a.P(2)};a.l&&setTimeout(q,0)})()}();c[b].lv="1";return c[b]}var o="lightningjs",k=window[o]=g(o);k.require=g;k.modules=c}({});window.usabilla_live = lightningjs.require("usabilla_live", "//w.usabilla.com/232bf8c2bee0.js");SpilGames(["TrackerData","Portal"],function(c,b){c.getCommonData({},function(a){a.siteid=b.get("siteid");a.channelid=b.get("channelid");window.usabilla_live("data",{custom:a})},!1)});
/* Games */
SpilGames(["SWP","Utils","FeatureDetector","Cookie"],function(f,e,g,h){var b={ws:"websockets",ww:"webworkers",tr:"transitions",an:"animations",cv:"canvas",gl:"webgl",un:"unity",th:"touch",fl:"flash",sw:"screenWidth",sh:"screenHeight"},d={},k=function(a){var c;return(a||"").split("-").reduce(function(a,b){if(c=b.match(/(w{2})(.*)/))a[c[1]]=parseInt(c[2],10);return a},{})},l=function(a){return e.keys(a).reduce(function(c,b){c.push(b+a[b]);return c},[]).join("-")},m=function(a){return e.keys(a).reduce(function(c,
d){b[d]&&(c[b[d]]=a[d]);return c},{})};g.cookies()&&(f.init("feature_collector"),f.System.init(function(a){if("features.detect"===a.name||"game.display"===a.name)d=k(h.getItem("fd")),e.keys(b).forEach(function(a){d[a]=g[b[a]]()|0}),SpilGames("tracker.event.track",{eventCategory:"page",eventAction:"features",eventLabel:navigator.userAgent,properties:m(d)}),h.setItem({expires:"never",domain:"",path:"/",key:"fd",value:l(d)})}))});
/* Games */
SpilGames("SWP DOMSelect Slider Utils BeLazy Tooltip".split(" "),function(a,c,l,m,f,n){a.init("segmentation_recommendations");var b=window.document.getElementById("wdg_segmentation_recommendations"),d=a.getProperty("ui_format")||"slider",p=a.getProperty("async")||!1,q=a.getProperty("pagesize")||4,r=a.getProperty("enable_tooltip"),t=a.getProperty("parent"),g=function(){},e=g,h=g;"slider"===d&&new l({slide:c.get(".slider-slide",b),prev:c.get(".slider-prev",b),next:c.get(".slider-next",b),duration:.4,
easing:"ease"});p&&(e=m.once(function(){a.Widget.refresh({async:!1,pagesize:q,lazyload_images:!0,ui_format:d,parent:t},{callback:function(){f.handleImagesIn(b)}})}),f.until("visible",b,e));r&&n.create(".wdg_segmentation_recommendations .game-thumb");"grid"===d&&(h=function(){var k=c.get("ul.grid-row",b);a.Utils.removeClass(b,["full-row","col-m","col-l"]);a.Utils.addClass(k,["col-m-2","col-l-4"]);a.Utils.removeClass(k,["col-m-4","col-l-6"])});a.System.init(function(a){"game.sidepanel.open"===a.name&&
a.data&&"segmentation_recommendations"===a.data.item&&e();"recent.played.filled"===a.name&&h()})});
/* Games */
SpilGames(["SWP","Utils"],function(a,c){a.init("social_share");var d=document.querySelectorAll("#wdg_social_share a[data-props]"),e=a.getProperty("game_id"),f=function(b){return"shareOn"+b.replace(/(?:^|_)([a-z])/g,function(b,a){return a.toUpperCase()})};c.each(d,function(b){b.addEventListener("click",function(){var a=b.getAttribute("data-props");SpilGames("tracker.event.express",{data:{eventCategory:"page",eventAction:"gamePageFeature",eventLabel:f(a),properties:{applicationId:e}}})})})});
/* Games */
SpilGames(["SWP","SWPUtils"],function(b,c){b.init("header");var a=document.querySelector(".wdg_header .authentication");b.System.init(function(b){switch(b.name){case "popup.header.open":window.setTimeout(function(){c.addClass(a,"is-open")},0);break;case "popup.header.close":c.removeClass(a,"is-open")}},!0)});SpilGames(["SWPUtils","DOMEvent","FeatureDetector"],function(b,c,a){function k(b,a){function c(){d=!1;b()}var d;return function(){d||(d=!0,e.setTimeout(c,a))}}if(a.transitions()){var e=window;a=e.document;var g=a.querySelector(".inner.container"),f=a.querySelector("#wdg_header > .inner"),d=!0,h;g&&f&&c.add(e,"scroll",k(function(){var a=e.pageYOffset,c=a-h||0;d&&0<c&&100<a?"left"!==g.getAttribute("data-offcanvas")&&(b.addClass(f,"sticky-hidden"),d=!1):!d&&0>c&&(b.removeClass(f,"sticky-hidden"),d=!0);
h=a},200))}});
/* Games */
SpilGames(["SWP","DOMEvent","DOMSelect","ThumbnailTracker"],function(c,f,b,m){function h(){d=!1;c.Utils.removeClass(g,"is-open");e&&e.removeAttribute("data-offcanvas")}var k=window;b=k.document;var d,e=b.querySelector(".inner.container"),g=b.getElementById("wdg_accordion_menu"),l=Array.prototype.slice.call(b.querySelectorAll(".accordion-item",g));f.add(b,"click",function(a){if(d){a=a||k.event;for(a=a.target||a.srcElement;a;){if(c.Utils.hasClass(a,"wdg_accordion_menu"))return;a=a.parentNode}h()}});
f.add(".browse-toggle","click",function(){d?h():(d=!0,c.Utils.addClass(g,"is-open"),e&&e.setAttribute("data-offcanvas","left"))});f.add(l,"click",function(a){function b(a){return a&&"BODY"!==a.tagName?-1<a.className.indexOf("accordion-item")?a:b(a.parentNode):!1}a=b(a.target);var d=c.Utils.hasClass(a,"accordion-open");l.forEach(function(a){c.Utils.removeClass(a,"accordion-open")});d||c.Utils.addClass(a,"accordion-open")})});
/* Games */
SpilGames(["SWP","DOMSelect","Utils","BeLazy"],function(a,b,f,c){a.init("segmentation_recommendations_menu");var d=window.document.getElementById("wdg_segmentation_recommendations_menu");b=a.getProperty("async")||!1;var g=a.getProperty("pagesize")||4,e=function(){};b&&(e=f.once(function(){a.Widget.refresh({async:!1,pagesize:g,lazyload_images:!0},{callback:function(){c.handleImagesIn(d)}})}),c.until("visible",d,e))});
/* Games */
SpilGames(["SWPUtils","DOMEvent","DOMSelect","ThumbnailTracker","BeLazy"],function(c,d,m,h,q){function n(a){a=a.currentTarget;var b=a.getAttribute("data-menu-id"),b=e.querySelector(".dropdown-wrapper [data-menu-id="+b+"]");c.addClass(a,"is-open");b&&b.setAttribute("data-offcanvas","open")}function p(){c.removeClass(k,"is-open");if(g)for(var a=0,b=g.length;a<b;a++)g[a].removeAttribute("data-offcanvas")}function l(){if(g)for(var a=0,b=k.length;a<b;a++)c.removeClass(k[a],"is-open")}var e=window.document,
g=e.querySelectorAll(".menu-dropdown-item"),f=e.getElementById("wdg_menu"),r=Array.prototype.slice.call(e.querySelectorAll(".horizontale-item")),k=e.querySelectorAll(".horizontale-item");d.add(".horizontale-item","touchstart",function(a){var b=a.currentTarget;b.getAttribute("data-menu-id");c.hasClass(b,"is-open")?(c.removeClass(f,"is-open"),l()):(l(),c.addClass(f,"is-open"),p(),n(a))});d.add(".horizontale-item","mouseenter",function(a){l();p();n(a)});d.add(".wdg_menu","mouseleave",function(){c.removeClass(f,
"is-open")});d.add(".wdg_menu","mouseenter",function(){c.addClass(f,"is-open")});d.add(r,"mouseenter",function(a){a=a.currentTarget.getAttribute("data-menu-id");a=f.querySelector(".dropdown-wrapper [data-menu-id="+a+"]");c.each(m.getAll("a[data-path]",a),h.trackElement);window.setTimeout(q.trigger,800)});d.add(".mobile-menu","click",function(a){h.trackElement(a.target);c.each(m.getAll("a[data-path]",a.target.parent),h.trackElement)})});
/* Games */
SpilGames(["SWP","Cookie","Net","DOMEvent","FeatureDetector"],function(c,n,p,q,r){c.init("players_online");var d=window,e=d.document,f=e.getElementById("players_online_num"),h=c.getProperty("*")||{},k=h.appid,t=c.get("spilgames.module.spapi.backend"),g=h.players_online,u=r.pageVisibility(),v=function(a){f.innerHTML=a+"";c.Utils.addClass(f,"highlight");d.setTimeout(function(){c.Utils.removeClass(f,"highlight")},500)},l=function(){p.send({url:t+"v1/players-online/"+k+"",headers:{"x-auth-token":n.getItem("token")}},
function(a){var b;if(b=!a.isError)b=a.n,b=!isNaN(parseFloat(b))&&isFinite(b);b&&a.n!==g&&(g=a.n,v(g))})},m=function(){u&&"visible"!==e.visibilityState||l();d.setTimeout(m,2E4)};k&&(d.setTimeout(m,1E4),q.add(e,"visibilitychange",function(){"visible"===e.visibilityState&&l()}))});
/* Games */
SpilGames(['PerformanceTracker'], function (RUM) {
        RUM.track();
    });
/* Games */
window.lightningjs||function(c){function g(b,d){d&&(d+=(/\?/.test(d)?"&":"?")+"lv=1");c[b]||function(){var i=window,h=document,j=b,g=h.location.protocol,l="load",k=0;(function(){function b(){a.P(l);a.w=1;c[j]("_load")}c[j]=function(){function m(){m.id=e;return c[j].apply(m,arguments)}var b,e=++k;b=this&&this!=i?this.id||0:0;(a.s=a.s||[]).push([e,b,arguments]);m.then=function(b,c,h){var d=a.fh[e]=a.fh[e]||[],j=a.eh[e]=a.eh[e]||[],f=a.ph[e]=a.ph[e]||[];b&&d.push(b);c&&j.push(c);h&&f.push(h);return m};return m};var a=c[j]._={};a.fh={};a.eh={};a.ph={};a.l=d?d.replace(/^\/\//,(g=="https:"?g:"http:")+"//"):d;a.p={0:+new Date};a.P=function(b){a.p[b]=new Date-a.p[0]};a.w&&b();i.addEventListener?i.addEventListener(l,b,!1):i.attachEvent("on"+l,b);var q=function(){function b(){return["<head></head><",c,' onload="var d=',n,";d.getElementsByTagName('head')[0].",d,"(d.",g,"('script')).",i,"='",a.l,"'\"></",c,">"].join("")}var c="body",e=h[c];if(!e)return setTimeout(q,100);a.P(1);var d="appendChild",g="createElement",i="src",k=h[g]("div"),l=k[d](h[g]("div")),f=h[g]("iframe"),n="document",p;k.style.display="none";e.insertBefore(k,e.firstChild).id=o+"-"+j;f.frameBorder="0";f.id=o+"-frame-"+j;/MSIE[ ]+[6|7|8]/.test(navigator.userAgent)&&(f[i]="javascript:false");f.allowTransparency="true";l[d](f);try{f.contentWindow[n].open()}catch(s){a.domain=h.domain,p="javascript:var d="+n+".open();d.domain='"+h.domain+"';",f[i]=p+"void(0);"}try{var r=f.contentWindow[n];r.write(b());r.close()}catch(t){f[i]=p+'d.write("'+b().replace(/"/g,String.fromCharCode(92)+'"')+'");d.close();'}a.P(2)};a.l&&setTimeout(q,0)})()}();c[b].lv="1";return c[b]}var o="lightningjs",k=window[o]=g(o);k.require=g;k.modules=c}({});window.usabilla_live = lightningjs.require("usabilla_live", "");SpilGames(["TrackerData","Portal"],function(c,b){c.getCommonData({},function(a){a.siteid=b.get("siteid");a.channelid=b.get("channelid");window.usabilla_live("data",{custom:a})},!1)});